name: Build Examples

on:
  pull_request:
    branches:
      - master
    paths:
      - 'examples/**'
      - '.github/workflows/**'
  push:
    branches:
      - master
    paths:
      - 'examples/**'
      - '.github/workflows/**'

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        run: |
          JSON=$(cat ./examples/manifest.json | jq [.[][]])
          JSON="${JSON//'%'/'%25'}"
          JSON="{\"include\":$JSON}"
          JSON="${JSON//$'\n'/'%0A'}"
          JSON="${JSON//$'\r'/'%0D'}"
          echo $JSON
          echo "-----------------------"
          echo "::set-output name=matrix::$JSON"

  build:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.prepare.outputs.matrix)}}
    env:
      OS: ${{ matrix.os }}
      JAVA: ${{ matrix.java-version }}
      AWS_REGION: eu-west-1
    steps:
      - uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.javaVersion }}
      - name: Build with Maven
        if: ${{ matrix.dependencyManager == 'maven' }}
        run: mvn -B package --file ${{ matrix.directory }}/pom.xml
      - name: Build with Gradle
        if: ${{ matrix.dependencyManager == 'gradle' }}
        run: |
          cd ./${{ matrix.directory }}/
          ./gradlew build

  savepr:
    runs-on: ubuntu-latest
    name: Save PR number if running on PR by dependabot
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Create Directory and save issue
        run: |
          mkdir -p ./pr
          echo ${{ github.event.number }}
          echo ${{ github.event.number }} > ./pr/NR
      - uses: actions/upload-artifact@v2
        name: Updload artifact
        with:
          name: pr
          path: pr/
