AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Kafka Deserialization example with Kafka Lambda ESM

Globals:
  Function:
    Timeout: 20
    Runtime: java11
    MemorySize: 512
    Tracing: Active

Resources:
  JsonDeserializationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: org.demo.kafka.JsonDeserializationFunction::handleRequest
      Environment:
        Variables:
          JAVA_TOOL_OPTIONS: "-XX:+TieredCompilation -XX:TieredStopAtLevel=1"
          POWERTOOLS_LOG_LEVEL: DEBUG
          POWERTOOLS_SERVICE_NAME: JsonDeserialization
          POWERTOOLS_METRICS_NAMESPACE: JsonDeserializationFunction

  AvroDeserializationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: org.demo.kafka.AvroDeserializationFunction::handleRequest
      Environment:
        Variables:
          JAVA_TOOL_OPTIONS: "-XX:+TieredCompilation -XX:TieredStopAtLevel=1"
          POWERTOOLS_LOG_LEVEL: DEBUG
          POWERTOOLS_SERVICE_NAME: AvroDeserialization
          POWERTOOLS_METRICS_NAMESPACE: AvroDeserializationFunction

  ProtobufDeserializationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: org.demo.kafka.ProtobufDeserializationFunction::handleRequest
      Environment:
        Variables:
          JAVA_TOOL_OPTIONS: "-XX:+TieredCompilation -XX:TieredStopAtLevel=1"
          POWERTOOLS_LOG_LEVEL: DEBUG
          POWERTOOLS_SERVICE_NAME: ProtobufDeserialization
          POWERTOOLS_METRICS_NAMESPACE: ProtobufDeserializationFunction

Outputs:
  JsonFunction:
    Description: "Kafka JSON Lambda Function ARN"
    Value: !GetAtt JsonDeserializationFunction.Arn
  AvroFunction:
    Description: "Kafka Avro Lambda Function ARN"
    Value: !GetAtt AvroDeserializationFunction.Arn
  ProtobufFunction:
    Description: "Kafka Protobuf Lambda Function ARN"
    Value: !GetAtt ProtobufDeserializationFunction.Arn
