name: Build

on:
  pull_request:
    branches:
      - main
    paths:
      - 'powertools-batch/**'
      - 'powertools-cloudformation/**'
      - 'powertools-core/**'
      - 'powertools-e2e-tests/**'
      - 'powertools-idempotency/**'
      - 'powertools-large-messages/**'
      - 'powertools-logging/**'
      - 'powertools-metrics/**'
      - 'powertools-parameters/**'
      - 'powertools-serialization/**'
      - 'powertools-sqs/**'
      - 'powertools-test-suite/**'
      - 'powertools-tracing/**'
      - 'powertools-validation/**'
      - 'examples/**'
      - 'pom.xml'
      - 'examples/pom.xml'
      - '.github/workflows/**'
  push:
    branches:
      - main
    paths:
      - 'powertools-batch/**'
      - 'powertools-cloudformation/**'
      - 'powertools-core/**'
      - 'powertools-e2e-tests/**'
      - 'powertools-idempotency/**'
      - 'powertools-large-messages/**'
      - 'powertools-logging/**'
      - 'powertools-metrics/**'
      - 'powertools-parameters/**'
      - 'powertools-serialization/**'
      - 'powertools-sqs/**'
      - 'powertools-test-suite/**'
      - 'powertools-tracing/**'
      - 'powertools-validation/**'
      - 'examples/**'
      - 'pom.xml'
      - 'examples/pom.xml'
      - '.github/workflows/**'

permissions:
  contents: read

jobs:
  build-corretto:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        java: [8, 11, 17, 21]
    name: Java ${{ matrix.java }}
    env:
      JAVA: ${{ matrix.java }}
      AWS_REGION: eu-west-1
    permissions:
      id-token: write # needed to interact with GitHub's OIDC Token endpoint.
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9  # v3.5.3
      - name: Setup java
        uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2 # v3.11.0
        with:
          distribution: 'corretto'
          java-version: ${{ matrix.java }}
          cache: 'maven'
      - name: Build with Maven
        run: mvn -B install --file pom.xml
      - name: Build Gradle Setup
        if: ${{ matrix.java == '8' }} # Gradle example can only be built on Java 8
        working-directory: examples/powertools-examples-core/gradle
        run: |
          curl -L -o gradle/wrapper/gradle.zip https:$(cat gradle/wrapper/gradle-wrapper.properties  | grep distributionUrl | cut -d ':' -f 2)
          unzip gradle/wrapper/gradle.zip -d gradle/wrapper/gradle
          ./gradle/wrapper/gradle/gradle-8.2.1/bin/gradle wrapper
      - name: Build Gradle Example - Java
        if: ${{ matrix.java == '8' }} # Gradle example can only be built on Java 8
        working-directory: examples/powertools-examples-core/gradle
        run: ./gradlew build

      - name: Build Gradle Setup (Kotlin)
        if: ${{ matrix.java == '8' }} # Gradle example can only be built on Java 8
        working-directory: examples/powertools-examples-core/kotlin
        run: |
          curl -L -o gradle/wrapper/gradle.zip https:$(cat gradle/wrapper/gradle-wrapper.properties  | grep distributionUrl | cut -d ':' -f 2)
          unzip gradle/wrapper/gradle.zip -d gradle/wrapper/gradle
          ./gradle/wrapper/gradle/gradle-8.2.1/bin/gradle wrapper
      - name: Build Gradle Example - Kotlin
        if: ${{ matrix.java == '8' }} # Gradle example can only be built on Java 8
        working-directory: examples/powertools-examples-core/kotlin
        run: ./gradlew build
        
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@d9f34f8cd5cb3b3eb79b3e4b5dae3a16df499a70 # v3.1.1
        if: ${{ matrix.java == '11' }} # publish results once
        with:
          files: ./powertools-cloudformation/target/site/jacoco/jacoco.xml,./powertools-core/target/site/jacoco/jacoco.xml,./powertools-idempotency/target/site/jacoco/jacoco.xml,./powertools-logging/target/site/jacoco/jacoco.xml,./powertools-metrics/target/site/jacoco/jacoco.xml,./powertools-parameters/target/site/jacoco/jacoco.xml,./powertools-serialization/target/site/jacoco/jacoco.xml,./powertools-sqs/target/site/jacoco/jacoco.xml,./powertools-tracing/target/site/jacoco/jacoco.xml,./powertools-validation/target/site/jacoco/jacoco.xml,./powertools-large-messages/target/site/jacoco/jacoco.xml,./powertools-batch/target/site/jacoco/jacoco.xml
  savepr:
    runs-on: ubuntu-latest
    name: Save PR number if running on PR by dependabot
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Create Directory and save issue
        run: |
          mkdir -p ./pr
          echo ${{ github.event.number }}
          echo ${{ github.event.number }} > ./pr/NR
      - uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        name: Upload artifact
        with:
          name: pr
          path: pr/
