on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: Semver version to release
      snapshot:
        type: boolean
        description: Create snapshot release
        default: true
      skip_publish:
        type: boolean
        description: Ship publish to Maven Central
        default: false

name: Release
run-name: Release

permissions: 
  contents: read

jobs:
  version_seal:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - id: version
        name: version
        uses: ./.github/version
        with:
          new_version: ${{ inputs.version }}
      - id: seal
        name: seal
        uses: ./.github/seal
        with:
          prefix: source