# Runs OSV scan
# 
# Description:
#   Checks dependencies already in the project for known issues
#
# Triggers:
#   - pull_request 
#   - workflow_dispatch
#   - cron
#   - push

on:
  pull_request:
    branches: 
      - main
  workflow_dispatch: {}
  schedule:
    - cron: "30 12 * * 1"
  push:
    branches:
      - main

name: OpenSource Vulnerability Scanner
run-name: OpenSource Vulnerability Scanner

permissions:
  contents: read

jobs:
  scan-pr:
    permissions:
      actions: read
      contents: read
      security-events: write
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@b00f71e051ddddc6e46a193c31c8c0bf283bf9e6 # v2.1.0
