# Dependency checks
#
# Description:
#   Verifies that dependencies are compatible with our project
#   by checking licenses and their security posture
#
# Triggers:
#   - pull_request

on:
  pull_request:

name: Verify Dependencies
run-name: Verify Dependencies – ${{ github.event_name }}

permissions: {}

jobs:
  verify:
    runs-on: ubuntu-latest
    permissions:
      contents: read       # checkout repository and read dependency snapshots
      pull-requests: write # post review comments
    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Verify Contents
        uses: actions/dependency-review-action@a1d282b36b6f3519aa1f3fc636f609c47dddb294 # v5.0.0
        with:
          config-file: './.github/dependency-review-config.yml'
